name: Xteam coding challenges
title: Xteam coding challenges
theme: jekyll-theme-cayman
baseurl: /weekly-challenges

collections:
  challenges:
    output: true
    permalink: /challenges/:path

defaults:
  - scope:
      path: ""
    values:
      layout: default